<?php

/**
 * @file
 * Contains recipe.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function recipe_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the recipe module.
    case 'help.page.recipe':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module that handle recipes') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function recipe_theme() {
  return [
    'recipe' => [
      'render element' => 'children',
    ],
  ];
}
